### ISSUE TITLE
Mass vehicle name updater doesn't actually work

### ISSUE THREAD

**Issue by pjreed** [swri-robotics/bag-database#44]
As noted in a comment, the change at https://github.com/swri-robotics/bag-database/commit/22dac9cbec3ed8a6c10cde3a0ea74d66e012c049 inadvertently removed a line from the vehicle name updater that actually saved the name to the bag file.  This would result in doing a name scan from the admin console having no actual effect.

**Comment by cbandera** [comment]
When looking at the code, I also got confused, because there is duplicate Code in "BagScanner" and in "BagService". One that is being called with new db entries, and one that is called on existing entries.
Maybe, this could be simplified, by extracting the actual extraction of the vehicle_name from the `BagFile` object into a seperate function...
