### ISSUE TITLE
The file still exists in explorer after the file is deleted from the volume folder

### ISSUE THREAD

**Issue by tngan** [swri-robotics/bag-database#49]
I put 3 bags in the mounted volume (default is /bag/location), the explorer shows properly. However, when I delete one of them and refresh the explorer, all 3 bags are still there even though the remote folder (/data) inside the container remains 2 files.

If the volume is only used for uploading purpose, it would be better to allow deleting files from screen.

**Comment by pjreed** [comment]
Currently, if a bag has disappeared from the file system, it won't be removed from the database, but instead its text will be italicized to indicate that it's missing.  Missing entries can be removed from the database with the "Remove DB Entries for Missing Bags" button in the Administration panel.

I originally did this because I thought that, since users can enter custom metadata for bag files, users might not want those entries to automatically disappear just because the file is gone.  Do you think it'd make sense to automatically remove entries?  (or maybe it would be better to have a config option for it?)

**Comment by tngan** [comment]
@pjreed Thanks for clarification. Basically, I do think the entries should be deleted if the file is gone, users should understand what they are doing. Or, if we want to keep the history, we may want to archive the records instead of delete everything.
