### ISSUE TITLE
Wrong start and end times

### ISSUE THREAD

**Issue by clecocel** [swri-robotics/bag-database#71]
It turns out that for many of our bag files the start and end times displayed are wrong (see below for an example). The duration is correct however for those files.

Would you know what could cause this or how to fix it?

Highlighted blue line is the one of interest
![screenshot from 2017-05-17 16-05-48](https://cloud.githubusercontent.com/assets/7353929/26179964/481d5a38-3b1b-11e7-8b7a-7f2830f6ea4b.png)
![screenshot from 2017-05-17 16-04-49](https://cloud.githubusercontent.com/assets/7353929/26179984/7d6699e8-3b1b-11e7-9a3c-74ab0c25cb64.png)

**Comment by pjreed** [comment]
It finds the start & end times by iterating over all of the [ChunkInfo](http://wiki.ros.org/Bags/Format/2.0#Chunk_info) records in a bag file and selecting the earliest "start time" and the latest "end time" that it can find.  It seems really strange that it would get the times wrong but the duration right, because it calculates the duration by simply subtracting the start time from the end time.  Do you have a fairly small bag file you could give me that demonstrates the problem?

**Comment by clecocel** [comment]
I can probably send you a small bag file that exhibits this behavior. What would be a good way to send it to you?

**Comment by pjreed** [comment]
If it's small enough to attach it to a GitHub issue (10 MB), putting it here is fine.

**Comment by clecocel** [comment]
Here's a very small fake bag that demonstrates the issue.

[test.bag.zip](https://github.com/swri-robotics/bag-database/files/1011590/test.bag.zip)

<img width="1190" alt="screen shot 2017-05-18 at 9 32 43 am" src="https://cloud.githubusercontent.com/assets/7353929/26213241/2c0108da-3bad-11e7-9ca6-095f39279fdb.png">

**Comment by pjreed** [comment]
Good news!  The dates are being extracted from the bag file and stored in the database properly.  It's the Javascript-side renderer that's putting the wrong value in there.  Will be an easy fix.
